
[Components.builtin_steering]

Usable = false
PortKind = "builtin"
InputPins = [
	{ Position = { X = -12.0, Y = 0.0 } },
	{ Position = { X = 12.0, Y = 0.0 } }
]

[Components.builtin_acceleration]

Usable = false
PortKind = "builtin"
InputPins = [
	{ Position = { X = -12.0, Y = 0.0 } }
]

[Components.builtin_braking]

Usable = false
PortKind = "builtin"
InputPins = [
	{ Position = { X = -12.0, Y = 0.0 } }
]


[Components.add]

Usable = true
PortKind = "chip"
InputPins = [
	{ Position = { X = -12.0, Y = 8.0 } },
	{ Position = { X = -12.0, Y = 0.0 } },
	{ Position = { X = -12.0, Y = -8.0 } }
]
OutputPins = [
	{ Position = { X = 12.0, Y = 0.0 } }
]

[Components.subtract]

Usable = true
PortKind = "chip"
InputPins = [
	{ Position = { X = -12.0, Y = 8.0 } },
	{ Position = { X = -12.0, Y = -8.0 } }
]
OutputPins = [
	{ Position = { X = 12.0, Y = 0.0 } }
]

[Components.split_signal]

Usable = true
PortKind = "chip"
InputPins = [
	{ Position = { X = -12.0, Y = 0.0 } },
]
OutputPins = [
	{ Position = { X = 12.0, Y = 8.0 } },
	{ Position = { X = 12.0, Y = 0.0 } },
	{ Position = { X = 12.0, Y = -8.0 } }
]

[Components.compare_equals]

Usable = true
PortKind = "chip"
InputPins = [
	{ Position = { X = -12.0, Y = 8.0 } },
	{ Position = { X = -12.0, Y = -8.0 } }
]
OutputPins = [
	{ Position = { X = 12.0, Y = 0.0 } }
]

[Components.multiply]

Usable = true
PortKind = "chip"
InputPins = [
	{ Position = { X = -12.0, Y = 8.0 } },
	{ Position = { X = -12.0, Y = 0.0 } },
	{ Position = { X = -12.0, Y = -8.0 } }
]
OutputPins = [
	{ Position = { X = 12.0, Y = 0.0 } }
]

[Components.constant]

Usable = true
PortKind = "chip"
OutputPins = [
	{ Position = { X = 12.0, Y = 8.0 } },
	{ Position = { X = 12.0, Y = 0.0 } },
	{ Position = { X = 12.0, Y = -8.0 } }
]


[Components.radar]

Usable = true
PortKind = "sensor"
OutputPins = [
	{ Position = { X = -0.0, Y = -16.0 } }
]

[Components.radar_shortrange]

Usable = true
PortKind = "sensor"
OutputPins = [
	{ Position = { X = -0.0, Y = -16.0 } }
]

[Components.road_sensor]

Usable = true
PortKind = "sensor"
OutputPins = [
	{ Position = { X = -0.0, Y = -16.0 } }
]

[[Ports]]
PortKind = "builtin"
HoodPosition = { X = 36.0, Y = 20.0 }
Prefill = "builtin_steering"

[[Ports]]
PortKind = "builtin"
HoodPosition = { X = 104.0, Y = 20.0 }

[[Ports]]
PortKind = "builtin"
HoodPosition = { X = 154.0, Y = 20.0 }
Prefill = "builtin_acceleration"

[[Ports]]
PortKind = "builtin"
HoodPosition = { X = 215.0, Y = 20.0 }
Prefill = "builtin_braking"


# Left forward sensor
[[Ports]]
WorldPosition = { X = 7.0, Y = 5.0 }
HoodPosition = { X = 71.0, Y = 230.0 }
Direction = { X = 1.0, Y = 0.0 }

PortKind = "sensor"

# Center forward sensor
[[Ports]]
WorldPosition = { X = 7.0, Y = 0.0 }
HoodPosition = { X = 128.0, Y = 225.0 }
Direction = { X = 1.0, Y = 0.0 }

PortKind = "sensor"

# Right forward sensor
[[Ports]]
WorldPosition = { X = 7.0, Y = -5.0 }
HoodPosition = { X = 185.0, Y = 230.0 }
Direction = { X = 1.0, Y = 0.0 }

PortKind = "sensor"

# Left diagonal sensor
[[Ports]]
WorldPosition = { X = 6.0, Y = 5.0 }
HoodPosition = { X = 25.0, Y = 215.0 }
Direction = { X = 1.0, Y = 1.0 }

PortKind = "sensor"

# Right diagonal sensor
[[Ports]]
WorldPosition = { X = 6.0, Y = -5.0 }
HoodPosition = { X = 226.0, Y = 215.0 }
Direction = { X = 1.0, Y = -1.0 }

PortKind = "sensor"

# Left side sensor
[[Ports]]
WorldPosition = { X = 3.0, Y = 5.0 }
HoodPosition = { X = 20.0, Y = 175.0 }
Direction = { X = 0.0, Y = 1.0 }

PortKind = "sensor"

# Right side sensor
[[Ports]]
WorldPosition = { X = 3.0, Y = -5.0 }
HoodPosition = { X = 241.0, Y = 175.0 }
Direction = { X = 0.0, Y = -1.0 }

PortKind = "sensor"


# Upper block of chips

[[Ports]]
HoodPosition = { X = 71.0, Y = 189.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 102.0, Y = 189.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 153.0, Y = 189.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 185.0, Y = 189.0 }

PortKind = "chip"


[[Ports]]
HoodPosition = { X = 71.0, Y = 157.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 102.0, Y = 157.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 153.0, Y = 157.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 185.0, Y = 157.0 }

PortKind = "chip"


# Center block of chips

[[Ports]]
HoodPosition = { X = 32.0, Y = 125.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 64.0, Y = 125.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 96.0, Y = 125.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 128.0, Y = 125.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 160.0, Y = 125.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 192.0, Y = 125.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 224.0, Y = 125.0 }

PortKind = "chip"


[[Ports]]
HoodPosition = { X = 32.0, Y = 93.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 64.0, Y = 93.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 96.0, Y = 93.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 128.0, Y = 93.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 160.0, Y = 93.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 192.0, Y = 93.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 224.0, Y = 93.0 }

PortKind = "chip"


[[Ports]]
HoodPosition = { X = 32.0, Y = 61.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 64.0, Y = 61.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 96.0, Y = 61.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 128.0, Y = 61.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 160.0, Y = 61.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 192.0, Y = 61.0 }

PortKind = "chip"

[[Ports]]
HoodPosition = { X = 224.0, Y = 61.0 }

PortKind = "chip"

