Scale = 4.0
# 475x250 scales up to 1900x1000
Size = { X = 475.00, Y = 250.00 }

BackgroundSprite = "racetrack.png"

[[Walls]]
Pos = { X = 205.25, Y = 228.50 }
Size = { X = 129.25, Y = -3.75 }

[[Props]]
Pos = { X = 362.50, Y = 176.75 }
Name = "roadblock_h"

[[Props]]
Pos = { X = 199.75, Y = 131.25 }
Name = "roadblock_v"
